### ISSUE TITLE
Shakyground: out-of-memory error

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/riesgos-frontend#35]
Executing the service with the eq ‘quakeml:quakeledger/peru_29’ results in an out-of-memory exception from the server

**Comment by MichaelLangbein** [comment]
Seems to be working now. You guys fixed it, right?

**Comment by ruester** [comment]
Its a problem about the server-side caching mechanism... so it seems the memory cache was filled up completely.. after a restart of the docker container the cache is cleared and it works for now.
In the longterm we will decrease the number of entries being cached and increase the overall maximum memory usage of the JVM. But those steps will be done after the "deployment pause", so that the services are now up and running for the demonstration ;-)
We can still keep this issue open untill we have finally fixed this for the production server...

**Comment by ruester** [comment]
A new version of the WPS server is now published and this should be fixed now...
