### ISSUE TITLE
Assetmaster: does not read out coordinates?

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/riesgos-frontend#36]
When calling the Assetmaster-process with any bounding-box, I keep getting back a geo-json file with data in Chile.

**Comment by nbrinckm** [comment]
I was really worried about this issue as it seems that assetmaster completely ignores the bounding box.
However this is not the case.
It is only that assetmaster currently checks if the result is empty before it writes the result into files.
As it can't find any parts of the exposure models it stays with the existing file that is already included in the outputs folder (and in this case it is one for chile).

I will fix it to write the empty files out, so that you get the empty geojson file correctly.

**Comment by MichaelLangbein** [comment]
Thank you very much! 
BTW: obviously, it would be great to have some (dummy?)  exposure-data for Peru and even Ecuador, too. Camilo, am I right in guessing that you're the go-to-person for exposure data? :)

**Comment by ruester** [comment]
we rolled out a new version of assetmaster, but the demonstrator uses a wrong bbox for the peru showcase:
```
...
<wps:LiteralData>-33.2</wps:LiteralData>
```
Latitude must be instead something around -20 to -2 ...

@MichaelLangbein can you have a look at the calling of the assetmaster service in the peru showcase?

**Comment by MichaelLangbein** [comment]
Great! Will check this out immediately! Back in a few minutes ...

**Comment by MichaelLangbein** [comment]
Oooooh, I see what you did there :) You added data from the north of Chile, right? Cheeky :)

So yes, I used the wrong bbox for the exposure! Has been updated. 
Just to make sure I've got this right: 
What parameter-values should I use for querymode, schema and assettype? At the moment they are at 'intersects', 'SARA_v1.0', and 'res', respectively.

**Comment by ruester** [comment]
For now those are the only options and data available, otherwise @maxpittore should know which it will be in the future once everything is in place...

**Comment by MichaelLangbein** [comment]
Great! Thanks, guys! I'll close the issue for now. Good work :)
